In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# 1
df = pd.read_csv('/content/drive/MyDrive/Datasets/titanic.csv')

In [ ]:
# 2
df.head(5)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [ ]:
# 3
df.shape

(887, 8)

In [ ]:
# 4
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Survived                 887 non-null    int64
 1   Pclass                   887 non-null    int64
 2   Name                     887 non-null    object
 3   Sex                      887 non-null    object
 4   Age                      887 non-null    float64
 5   Siblings/Spouses Aboard  887 non-null    int64
 6   Parents/Children Aboard  887 non-null    int64
 7   Fare                     887 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.6+ KB

In [ ]:
# 5
df[['Age', 'Sex']]

      Age     Sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
882  27.0    male
883  19.0  female
884   7.0  female
885  26.0    male
886  32.0    male

[887 rows x 2 columns]

In [ ]:
# 6
df.isnull().sum()

Survived                   0
Pclass                     0
Name                       0
Sex                        0
Age                        0
Siblings/Spouses Aboard    0
Parents/Children Aboard    0
Fare                       0
dtype: int64

In [ ]:
# 7
df[df['Age'] > 18]

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
881,0,3,Mrs. William (Margaret Norton) Rice,female,39.0,0,5,29.1250
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [ ]:
# 8
df['Age'].mean()

29.471443066516347

In [53]:
# 9
df['IsChild'] = df['Age'] < 18

,Survived,Pclass,Name,Sex,Age,SibSp,Parents/Children Aboard,Fare,IsChild
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,False
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,False
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,False
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,False
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,False
...,...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000,False
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000,False
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500,True
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000,False
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500,False

In [ ]:
# 10
df.pivot_table(index='Pclass', values='Survived', aggfunc='mean')

        Survived
Pclass
1       0.629630
2       0.472826
3       0.244353

In [ ]:
# 11
df.groupby(['Pclass', 'Sex'])['Fare'].mean()

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.695466
Name: Fare, dtype: float64

In [40]:
# 12
df['Age'].fillna(df['Age'].median())

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
882    27.0
883    19.0
884     7.0
885    26.0
886    32.0
Name: Age, Length: 887, dtype: float64

In [46]:
# 13
df.dropna(subset='Age', inplace=True)

In [49]:
# 14
df.rename(columns={'Siblings/Spouses Aboard': 'SibSp'}, inplace=True)

In [57]:
# 15
df['Age'].value_counts()

Age
22.00    39
28.00    37
18.00    36
21.00    34
24.00    34
         ..
0.92      1
23.50     1
36.50     1
55.50     1
74.00     1
Name: count, Length: 89, dtype: int64

In [60]:
# 16
df['Survived'].nunique()

2

In [70]:
# 17
df.sort_values(by=['Age'], ascending=False)

,Survived,Pclass,Name,Sex,Age,SibSp,Parents/Children Aboard,Fare,IsChild
627,1,1,Mr. Algernon Henry Wilson Barkworth,male,80.00,0,0,30.0000,False
847,0,3,Mr. Johan Svensson,male,74.00,0,0,7.7750,False
490,0,1,Mr. Ramon Artagaveytia,male,71.00,0,0,49.5042,False
95,0,1,Mr. George B Goldschmidt,male,71.00,0,0,34.6542,False
115,0,3,Mr. Patrick Connors,male,70.50,0,0,7.7500,False
...,...,...,...,...,...,...,...,...,...
77,1,2,Master. Alden Gates Caldwell,male,0.83,0,2,29.0000,True
466,1,3,Miss. Helene Barbara Baclini,female,0.75,2,1,19.2583,True
641,1,3,Miss. Eugenie Baclini,female,0.75,2,1,19.2583,True
751,1,2,Master. Viljo Hamalainen,male,0.67,1,1,14.5000,True
799,1,3,Master. Assad Alexander Thomas,male,0.42,0,1,8.5167,True

In [71]:
# 18
df['SibSp'].sum()

466

In [78]:
# 19
subset = pd.DataFrame(df[['Survived', 'Fare']], index=df.index)
subset

     Survived     Fare
0           0   7.2500
1           1  71.2833
2           1   7.9250
3           1  53.1000
4           0   8.0500
..        ...      ...
882         0  13.0000
883         1  30.0000
884         0  23.4500
885         1  30.0000
886         0   7.7500

[887 rows x 2 columns]

In [82]:
# 20
df.groupby(df['Pclass'])['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.707707
Name: Fare, dtype: float64